### ISSUE TITLE
DOTFILES_ROOT/dotbro-macOS.toml missing

### ISSUE THREAD

**Issue by s3638844** [hypnoglow/dotfiles#1]
Hey looks like DOTFILES_ROOT/dotbro-macOS.toml and $DOTFILES_ROOT/dotbro-linux.toml got removed somewhere in the last couple of commits.

**Comment by hypnoglow** [comment]
`dotbro` files are now stored in [dotbro/](https://github.com/hypnoglow/dotfiles/tree/master/dotbro) directory, named the same way as the profile name. I changed this due to having multiple machines with the same OS.

If you have more questions, feel free to ask. I'll close this issue for now.
